# imagen base
FROM node:20 as base
WORKDIR /app
COPY package*.json ./
RUN npm ci

# imagen para compilar 
FROM base as builder
WORKDIR /app
COPY . .
RUN npm run build

# servidor web image
FROM nginx:stable as production                        
WORKDIR /app
COPY --from=builder /app/out /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# docker build -t gempresafe .
# docker run -p 8080:80 gempresafe
# http://localhost:8080/